//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionLogs
    {
        public int LogId { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public string ExecutionStatus { get; set; }
        public string OutputMessage { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
