//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTaskResults
    {
        public int ResultId { get; set; }
        public int UserTaskId { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public string ResultValue { get; set; }
    
        public virtual UserTask UserTask { get; set; }
    }
}
